name: HabbitApp
options:
  bundleIdPrefix: com.habbit
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: ko
targets:
  HabbitApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - HabbitApp
    dependencies:
      - target: HabbitAppWidget
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.boss.HabbitApp
        INFOPLIST_FILE: HabbitApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_ENTITLEMENTS: HabbitApp/HabbitApp.entitlements
    scheme:
      testTargets:
        - HabbitAppTests
      gatherCoverageData: false
  HabbitAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - HabbitAppTests
    dependencies:
      - target: HabbitApp
  HabbitAppWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - HabbitAppWidget
      - path: HabbitApp/Models
        buildPhase: sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.boss.HabbitApp.HabbitAppWidget
        INFOPLIST_FILE: HabbitAppWidget/Info.plist
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_ENTITLEMENTS: HabbitAppWidget/HabbitAppWidget.entitlements
schemes:
  HabbitApp:
    build:
      targets:
        HabbitApp: all
        HabbitAppWidget: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - HabbitAppTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  HabbitAppWidget:
    build:
      targets:
        HabbitAppWidget: all
    run:
      config: Debug

